<!--
  LedgerModal — Add / Edit a General Ledger (or Reserve Fund Ledger) account.
  WeConnectU "Financial Setup → General Ledger → Add General Ledger Account" clone.

  Emits `save` with the payload; the parent performs the request against /ledgers.
  When `fund === 'reserve'` this behaves as the Reserve Fund Ledger add form.
-->
<script setup>
import { ref, computed, watch } from 'vue'
import api from '@/composables/useApi'
import AppModal from '@/components/common/AppModal.vue'
import AppInput from '@/components/common/AppInput.vue'
import AppSelect from '@/components/common/AppSelect.vue'
import AppButton from '@/components/common/AppButton.vue'

const props = defineProps({
  show:    { type: Boolean, default: false },
  mode:    { type: String,  default: 'add' }, // 'add' | 'edit'
  ledger:  { type: Object,  default: null },
  options: { type: Object,  default: null },  // { main_accounts, financial_categories, account_types, tax_types }
  fund:    { type: String,  default: 'main' }, // 'main' | 'reserve'
  saving:  { type: Boolean, default: false },
  error:   { type: String,  default: null },
})

const emit = defineEmits(['close', 'save'])

const TYPE_OPTIONS = [
  { value: 'main', label: 'Main Account' },
  { value: 'sub',  label: 'Sub-Account' },
]

const form = ref(blank())
const localError = ref(null)
const codeLoading = ref(false)

function blank() {
  return {
    accountType: 'main',   // main | sub  (structure, not "Account Type" GL field)
    main_account_id: null, // parent when sub
    code: '',              // auto-fetched, read-only
    name: '',
    type: '',              // GL "Account Type" (Income Statement / Balance Sheet)
    category: '',          // Financial Category
    tax_type: '',          // Tax Type
    allow_sub_accounts: true,
  }
}

const title = computed(() =>
  props.mode === 'edit'
    ? (props.fund === 'reserve' ? 'Edit Reserve Fund Ledger Account' : 'Edit General Ledger Account')
    : (props.fund === 'reserve' ? 'Add Reserve Fund Ledger Account' : 'Add General Ledger Account'),
)

const mainAccountOptions = computed(() =>
  (props.options?.main_accounts ?? []).map(m => ({
    value: m.id,
    label: m.label ?? `${m.code} — ${m.name ?? ''}`.trim(),
  })),
)
const categoryOptions = computed(() => props.options?.financial_categories ?? [])
const accountTypeOptions = computed(() => props.options?.account_types ?? [])
const taxTypeOptions = computed(() => props.options?.tax_types ?? [])

const isSub = computed(() => form.value.accountType === 'sub')

watch(
  () => props.show,
  (open) => {
    if (!open) return
    localError.value = null
    if (props.mode === 'edit' && props.ledger) {
      const l = props.ledger
      form.value = {
        accountType: l.main_account_id ? 'sub' : 'main',
        main_account_id: l.main_account_id ?? null,
        code: l.code ?? '',
        name: l.name ?? '',
        type: l.type ?? '',
        category: l.category ?? '',
        tax_type: l.tax_type ?? '',
        allow_sub_accounts: l.allow_sub_accounts !== false,
      }
    } else {
      form.value = blank()
      fetchNextCode()
    }
  },
  { immediate: true },
)

// The account number is auto-generated by the server based on the chosen
// structure (and parent, for sub-accounts). Best-effort — degrade silently.
async function fetchNextCode() {
  if (props.mode === 'edit') return
  codeLoading.value = true
  form.value.code = ''
  try {
    const params = { fund: props.fund, type: form.value.accountType }
    if (isSub.value && form.value.main_account_id) params.main_account_id = form.value.main_account_id
    const { data } = await api.get('/ledgers/next-code', { params })
    form.value.code = data.code ?? data.data?.code ?? ''
  } catch {
    form.value.code = ''
  } finally {
    codeLoading.value = false
  }
}

watch(() => form.value.accountType, () => { if (props.show) fetchNextCode() })
watch(() => form.value.main_account_id, () => { if (props.show && isSub.value) fetchNextCode() })

function submit() {
  localError.value = null
  if (isSub.value && !form.value.main_account_id) {
    localError.value = 'Please select a main account.'
    return
  }
  if (!form.value.name.trim()) {
    localError.value = 'Please enter an account name.'
    return
  }
  if (!form.value.type) {
    localError.value = 'Please select an account type.'
    return
  }
  const payload = {
    fund:            props.fund,
    account_type:    form.value.accountType, // main | sub structure
    main_account_id: isSub.value ? form.value.main_account_id : null,
    name:            form.value.name.trim(),
    type:            form.value.type,
    category:        form.value.category || null,
    tax_type:        form.value.tax_type || null,
    allow_sub_accounts: isSub.value ? undefined : !!form.value.allow_sub_accounts,
  }
  emit('save', payload)
}
</script>

<template>
  <AppModal :show="show" size="lg" @close="emit('close')">
    <template #header>
      <h3 class="text-base font-bold text-[#1E2740] w-full text-center" style="font-family: 'DM Sans', sans-serif">
        {{ title }}
      </h3>
    </template>

    <div class="space-y-4">
      <div v-if="error || localError" class="rounded border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
        {{ error || localError }}
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AppSelect
          v-model="form.accountType"
          :options="TYPE_OPTIONS"
          label="Type"
          :disabled="mode === 'edit'"
        />

        <AppSelect
          v-if="isSub"
          v-model="form.main_account_id"
          :options="mainAccountOptions"
          label="Main Account"
          placeholder="Select main account…"
          required
        />
        <div v-else />

        <div class="flex flex-col gap-1.5">
          <label class="text-sm font-medium text-fg">Account Number</label>
          <div class="flex items-center h-11 px-4 rounded border border-border bg-muted/40 text-sm font-mono text-muted-foreground">
            <span v-if="codeLoading">Generating…</span>
            <span v-else>{{ form.code || '—' }}</span>
          </div>
        </div>

        <AppInput v-model="form.name" label="Account Name" placeholder="e.g. Levy Income" required />

        <AppSelect
          v-model="form.type"
          :options="accountTypeOptions"
          label="Account Type"
          placeholder="Select account type…"
          required
        />

        <AppSelect
          v-model="form.category"
          :options="categoryOptions"
          label="Financial Category"
          placeholder="Select financial category…"
        />

        <AppSelect
          v-model="form.tax_type"
          :options="taxTypeOptions"
          label="Tax Type"
          placeholder="Select tax type…"
        />
      </div>

      <!-- Main Account only → Editing / Locking -->
      <div v-if="!isSub" class="rounded-md border border-border bg-muted/20 px-4 py-3">
        <p class="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-2">Editing / Locking</p>
        <label class="flex items-center gap-2.5 text-sm text-foreground cursor-pointer select-none">
          <input v-model="form.allow_sub_accounts" type="checkbox" class="w-5 h-5 rounded accent-[#2f6fb0]" />
          Allow Sub-Accounts
        </label>
      </div>
    </div>

    <template #footer>
      <AppButton variant="outline" :disabled="saving" @click="emit('close')">Cancel</AppButton>
      <AppButton variant="primary" :loading="saving" @click="submit">
        {{ mode === 'edit' ? 'Save Changes' : 'Add Account' }}
      </AppButton>
    </template>
  </AppModal>
</template>
