<?php

namespace App\Enums;

enum InvoiceSource: string
{
    /** Generated by the recurring billing engine or a single-charge manual entry. */
    case SYSTEM = 'system';

    /** A WeConnectU-style multi-line customer invoice captured by a user. */
    case MANUAL = 'manual';

    /**
     * Return all enum values as a plain array (used in migrations).
     *
     * @return array<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
